### ISSUE TITLE
Interesting approach!

### ISSUE THREAD

**Issue by segfall** [webjsx/webjsx#5]
Not an issue :) Just a small congrats. 

I was looking for a small library that organizes my view layer, without introducing state management or framework complexity like React.
This one seems to fit my needs! So far, I've only had to rewrite handwritten HTML/JS into JSX. I'll see far I can productionize this before I hit boundaries.

Thanks for exploring this concept!

**Comment by jeswin** [comment]
If you run into issues, happy to jump in and help. Thanks for trying it out.

**Comment by jeswin** [comment]
@segfall I'll close this for now. If you need anything let me know please.

**Comment by segfall** [comment]
Alrighty! I'll write up a quick report on my experience so far. No action needed; these are my mostly unedited thoughts:

- I passed in an ArrayIterator instead of an Array for rendering
   - My fault, I don't think React supports ArrayIterators-- though React may have a better error message
- webjsx doesn't quite work out of the box with esbuild
   - My workaround: `{ loader: { '.js': 'jsx' } }` in the build file, and `window.React = webjsx` in my component file.
- Web Component's `defineElement` can only be invoked once in the lifetime of a page
   - Not an issue with your repo. It is a blocker for my use of Web Components in my repo, since it blocks HMR.
     - This has been a problem for years. https://github.com/WICG/webcomponents/issues/754 . 
     - Alternative workarounds I found either don't fit my specific dev environment (developing a plugin for an Electron app) or haven't been updated in years and are broken.
     
For now, I'll keep using webjsx in my own handwritten Components.

**Comment by jeswin** [comment]
If you need to see sample code using webjsx, you can check this: https://github.com/codespin-ai/codespin-chrome-extension/

**Comment by segfall** [comment]
Thanks for the link, your examples on stackblitz were informative as well.

However, I don't think I can use Web Components without Hot Module Reloading, so I'll try to figure out another approach to nesting components.

**Comment by segfall** [comment]
Alrighty, two updates. My last two most likely.

### Hacking around Web Components and HMR
I used a kludge to get around WebComponents refusing to re-define a custom element until a page reload. I wrote a custom subclass that changes the element's name to the class name + a semi-random string, see below:
```js
// Sub class
let start = Math.floor(window.performance.now());
let components = {}

export class WebElement extends HTMLElement {

    static get s() {
        if (!components[this.name]) {
            let name = this.name.replace(/[A-Z]/g, m => "-" + m.toLowerCase()).slice(1) + start;
            components[this.name] = name
            customElements.define(name, this);
        }
        return components[this.name];
    }

}
// Normal component class
class MyWebElement extends WebElement { 
...
```

I can then auto instantiate this custom component like so:
```js
        someContainer.innerHTML = `<${MyWebElement.s}></${MyWebElement.s}>` // this will register the element and resolve to a tagName that looks like  my-web-element13122,
```

I'm writing an Electron plugin on a Macbook M2 so I may be able to get away with this inefficiency. 

### Dropping Webjsx
I've decided to forgo it and use `lit-html`. Informal testing showed this library is one order magnitude slower than `lit-html`.
While I do enjoy the ergonomics of JSX, I'm starting to see why virtual doms have become less popular. But I'm not versed enough in framework design to comment beyond that. 

Anyway, thanks for the work on this library!

**Comment by jeswin** [comment]
Thanks for the update, and best of luck. 

I'm interested in working on the performance. In case you have it handy, can you share the performance test snippets please?
